require: rubocop-rspec

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/DotPosition:
  EnforcedStyle: trailing

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/EmptyLinesAroundBody:
  Description: "Keeps track of empty lines around expression bodies."
  Enabled: false

Style/RegexpLiteral:
  MaxSlashes: 0

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
